name: "Experimental 1st Git Workflow"
on:
 push: 
 pull_request:

jobs:
 checkout-and-ls:
   runs-on: windows-2022
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
          clean: true
     - name: List files in repository
       run: ls -la

