name: "Experimental 1st Git Workflow"
on:
 push: 
 pull_request:

jobs:
 checkout-and-ls:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v4
       with:
          clean: true
     - name: Git Submodules
       run: git submodule update --init
     - name: Cmake Build
       run: cmake -S . -B build
     - name: Cmake Compile
       run: cmake --build build
     - name: Run Selfcheck
       run: ./build/address_book_tests.exe





